INSERT INTO brand_series(name,brand_id) VALUES ('ALFA 4C', 1);
INSERT INTO brand_series(name,brand_id) VALUES ('Giulietta', 1);
INSERT INTO brand_series(name,brand_id) VALUES ('Gloria', 1);
INSERT INTO brand_series(name,brand_id) VALUES ('MiTo', 1);
INSERT INTO brand_series(name,brand_id) VALUES ('ALFA 147', 1);
INSERT INTO brand_series(name,brand_id) VALUES ('ALFA 156', 1);
INSERT INTO brand_series(name,brand_id) VALUES ('ALFA GT', 1);
INSERT INTO brand_series(name,brand_id) VALUES ('Cygnet', 2);
INSERT INTO brand_series(name,brand_id) VALUES ('Lagonda', 2);
INSERT INTO brand_series(name,brand_id) VALUES ('Rapide', 2);
INSERT INTO brand_series(name,brand_id) VALUES ('V12 Vantage', 2);
INSERT INTO brand_series(name,brand_id) VALUES ('V12 Zagato', 2);
INSERT INTO brand_series(name,brand_id) VALUES ('V8 Vantage', 2);
INSERT INTO brand_series(name,brand_id) VALUES ('Vanquish', 2);
INSERT INTO brand_series(name,brand_id) VALUES ('Virage', 2);
INSERT INTO brand_series(name,brand_id) VALUES ('阿斯顿·马丁DB5', 2);
INSERT INTO brand_series(name,brand_id) VALUES ('阿斯顿·马丁-阿斯顿·马丁DB9', 2);
INSERT INTO brand_series(name,brand_id) VALUES ('阿斯顿·马丁-阿斯顿·马丁DBS', 2);
INSERT INTO brand_series(name,brand_id) VALUES ('阿斯顿·马丁-阿斯顿·马丁One-77', 2);
INSERT INTO brand_series(name,brand_id) VALUES ('奥迪A3', 3);
INSERT INTO brand_series(name,brand_id) VALUES ('奥迪A4L', 3);
INSERT INTO brand_series(name,brand_id) VALUES ('奥迪A6L', 3);
INSERT INTO brand_series(name,brand_id) VALUES ('奥迪Q3', 3);
INSERT INTO brand_series(name,brand_id) VALUES ('奥迪Q5', 3);
INSERT INTO brand_series(name,brand_id) VALUES ('奥迪A4', 3);
INSERT INTO brand_series(name,brand_id) VALUES ('奥迪A6', 3);
INSERT INTO brand_series(name,brand_id) VALUES ('allroad', 3);
INSERT INTO brand_series(name,brand_id) VALUES ('Crosslane Coupe', 3);
INSERT INTO brand_series(name,brand_id) VALUES ('Nanuk', 3);
INSERT INTO brand_series(name,brand_id) VALUES ('quattro', 3);
INSERT INTO brand_series(name,brand_id) VALUES ('奥迪A1', 3);
INSERT INTO brand_series(name,brand_id) VALUES ('奥迪A2', 3);
INSERT INTO brand_series(name,brand_id) VALUES ('奥迪A3(进口)', 3);
INSERT INTO brand_series(name,brand_id) VALUES ('奥迪A4(进口)', 3);
INSERT INTO brand_series(name,brand_id) VALUES ('奥迪A5', 3);
INSERT INTO brand_series(name,brand_id) VALUES ('奥迪A6(进口)', 3);
INSERT INTO brand_series(name,brand_id) VALUES ('奥迪A7 ', 3);
INSERT INTO brand_series(name,brand_id) VALUES ('奥迪A8', 3);
INSERT INTO brand_series(name,brand_id) VALUES ('奥迪e-tron', 3);
INSERT INTO brand_series(name,brand_id) VALUES ('奥迪Q3(进口)', 3);
INSERT INTO brand_series(name,brand_id) VALUES ('奥迪Q5(进口)', 3);
INSERT INTO brand_series(name,brand_id) VALUES ('奥迪Q7', 3);
INSERT INTO brand_series(name,brand_id) VALUES ('奥迪R18', 3);
INSERT INTO brand_series(name,brand_id) VALUES ('奥迪R8', 3);
INSERT INTO brand_series(name,brand_id) VALUES ('奥迪S1', 3);
INSERT INTO brand_series(name,brand_id) VALUES ('奥迪S3', 3);
INSERT INTO brand_series(name,brand_id) VALUES ('奥迪S4', 3);
INSERT INTO brand_series(name,brand_id) VALUES ('奥迪S5', 3);
INSERT INTO brand_series(name,brand_id) VALUES ('奥迪S6', 3);
INSERT INTO brand_series(name,brand_id) VALUES ('奥迪S7', 3);
INSERT INTO brand_series(name,brand_id) VALUES ('奥迪S8', 3);
INSERT INTO brand_series(name,brand_id) VALUES ('奥迪SQ5', 3);
INSERT INTO brand_series(name,brand_id) VALUES ('奥迪TT', 3);
INSERT INTO brand_series(name,brand_id) VALUES ('奥迪TT offroad', 3);
INSERT INTO brand_series(name,brand_id) VALUES ('奥迪TTS', 3);
INSERT INTO brand_series(name,brand_id) VALUES ('奥迪Cross', 3);
INSERT INTO brand_series(name,brand_id) VALUES ('奥迪Urban', 3);
INSERT INTO brand_series(name,brand_id) VALUES ('奥迪RS 3', 3);
INSERT INTO brand_series(name,brand_id) VALUES ('奥迪RS 4', 3);
INSERT INTO brand_series(name,brand_id) VALUES ('奥迪RS 5', 3);
INSERT INTO brand_series(name,brand_id) VALUES ('奥迪RS 6', 3);
INSERT INTO brand_series(name,brand_id) VALUES ('奥迪RS 7', 3);
INSERT INTO brand_series(name,brand_id) VALUES ('奥迪RS Q3', 3);
INSERT INTO brand_series(name,brand_id) VALUES ('奥迪TT RS', 3);
INSERT INTO brand_series(name,brand_id) VALUES ('巴博斯 CLS级', 4);
INSERT INTO brand_series(name,brand_id) VALUES ('巴博斯 E级', 4);
INSERT INTO brand_series(name,brand_id) VALUES ('巴博斯 GL级', 4);
INSERT INTO brand_series(name,brand_id) VALUES ('巴博斯 G级', 4);
INSERT INTO brand_series(name,brand_id) VALUES ('巴博斯 M级', 4);
INSERT INTO brand_series(name,brand_id) VALUES ('巴博斯 SLK级', 4);
INSERT INTO brand_series(name,brand_id) VALUES ('巴博斯 SLS级', 4);
INSERT INTO brand_series(name,brand_id) VALUES ('巴博斯 SL级', 4);
INSERT INTO brand_series(name,brand_id) VALUES ('巴博斯 smart fortwo', 4);
INSERT INTO brand_series(name,brand_id) VALUES ('巴博斯 S级', 4);
INSERT INTO brand_series(name,brand_id) VALUES ('宝骏610', 5);
INSERT INTO brand_series(name,brand_id) VALUES ('宝骏630', 5);
INSERT INTO brand_series(name,brand_id) VALUES ('宝骏730', 5);
INSERT INTO brand_series(name,brand_id) VALUES ('乐驰', 5);
INSERT INTO brand_series(name,brand_id) VALUES ('宝马3系', 6);
INSERT INTO brand_series(name,brand_id) VALUES ('宝马5系', 6);
INSERT INTO brand_series(name,brand_id) VALUES ('宝马X1', 6);
INSERT INTO brand_series(name,brand_id) VALUES ('Active Tourer', 6);
INSERT INTO brand_series(name,brand_id) VALUES ('Gran Lusso', 6);
INSERT INTO brand_series(name,brand_id) VALUES ('Vision Future Luxury', 6);
INSERT INTO brand_series(name,brand_id) VALUES ('Zagato Coupe', 6);
INSERT INTO brand_series(name,brand_id) VALUES ('宝马1系', 6);
INSERT INTO brand_series(name,brand_id) VALUES ('宝马2系', 6);
INSERT INTO brand_series(name,brand_id) VALUES ('宝马2系Active Tourer', 6);
INSERT INTO brand_series(name,brand_id) VALUES ('宝马3系(进口)', 6);
INSERT INTO brand_series(name,brand_id) VALUES ('宝马3系GT', 6);
INSERT INTO brand_series(name,brand_id) VALUES ('宝马4系', 6);
INSERT INTO brand_series(name,brand_id) VALUES ('宝马5系(进口)', 6);
INSERT INTO brand_series(name,brand_id) VALUES ('宝马5系GT', 6);
INSERT INTO brand_series(name,brand_id) VALUES ('宝马6系', 6);
INSERT INTO brand_series(name,brand_id) VALUES ('宝马7系', 6);
INSERT INTO brand_series(name,brand_id) VALUES ('宝马i3', 6);
INSERT INTO brand_series(name,brand_id) VALUES ('宝马i8', 6);
INSERT INTO brand_series(name,brand_id) VALUES ('宝马X1(进口)', 6);
INSERT INTO brand_series(name,brand_id) VALUES ('宝马X3', 6);
INSERT INTO brand_series(name,brand_id) VALUES ('宝马X4', 6);
INSERT INTO brand_series(name,brand_id) VALUES ('宝马X5', 6);
INSERT INTO brand_series(name,brand_id) VALUES ('宝马X6', 6);
INSERT INTO brand_series(name,brand_id) VALUES ('宝马Z4', 6);
INSERT INTO brand_series(name,brand_id) VALUES ('ConnectedDrive', 6);
INSERT INTO brand_series(name,brand_id) VALUES ('EfficientDynamics', 6);
INSERT INTO brand_series(name,brand_id) VALUES ('Isetta', 6);
INSERT INTO brand_series(name,brand_id) VALUES ('宝马Z8', 6);
INSERT INTO brand_series(name,brand_id) VALUES ('宝马M3', 6);
INSERT INTO brand_series(name,brand_id) VALUES ('宝马M4', 6);
INSERT INTO brand_series(name,brand_id) VALUES ('宝马M5', 6);
INSERT INTO brand_series(name,brand_id) VALUES ('宝马M6', 6);
INSERT INTO brand_series(name,brand_id) VALUES ('宝马X5 M', 6);
INSERT INTO brand_series(name,brand_id) VALUES ('宝马X6 M', 6);
INSERT INTO brand_series(name,brand_id) VALUES ('宝马1系M', 6);
INSERT INTO brand_series(name,brand_id) VALUES ('宝马M1', 6);
INSERT INTO brand_series(name,brand_id) VALUES ('Boxster', 7);
INSERT INTO brand_series(name,brand_id) VALUES ('Cayman', 7);
INSERT INTO brand_series(name,brand_id) VALUES ('Macan', 7);
INSERT INTO brand_series(name,brand_id) VALUES ('Panamera', 7);
INSERT INTO brand_series(name,brand_id) VALUES ('保时捷911', 7);
INSERT INTO brand_series(name,brand_id) VALUES ('保时捷918', 7);
INSERT INTO brand_series(name,brand_id) VALUES ('卡宴', 7);
INSERT INTO brand_series(name,brand_id) VALUES ('Carrera GT', 7);
INSERT INTO brand_series(name,brand_id) VALUES ('北京40', 8);
INSERT INTO brand_series(name,brand_id) VALUES ('北京汽车B60', 8);
INSERT INTO brand_series(name,brand_id) VALUES ('北京汽车BC302Z', 8);
INSERT INTO brand_series(name,brand_id) VALUES ('北京汽车BJ80', 8);
INSERT INTO brand_series(name,brand_id) VALUES ('北京汽车C51X', 8);
INSERT INTO brand_series(name,brand_id) VALUES ('北京汽车C60', 8);
INSERT INTO brand_series(name,brand_id) VALUES ('北京汽车C71', 8);
INSERT INTO brand_series(name,brand_id) VALUES ('北京汽车E系列', 8);
INSERT INTO brand_series(name,brand_id) VALUES ('幻速S2', 9);
INSERT INTO brand_series(name,brand_id) VALUES ('幻速S3', 9);
INSERT INTO brand_series(name,brand_id) VALUES ('北汽威旺205', 10);
INSERT INTO brand_series(name,brand_id) VALUES ('北汽威旺306', 10);
INSERT INTO brand_series(name,brand_id) VALUES ('北汽威旺307', 10);
INSERT INTO brand_series(name,brand_id) VALUES ('北汽威旺M20', 10);
INSERT INTO brand_series(name,brand_id) VALUES ('北汽威旺T205-D', 10);
INSERT INTO brand_series(name,brand_id) VALUES ('BJ 212', 11);
INSERT INTO brand_series(name,brand_id) VALUES ('骑士S12', 11);
INSERT INTO brand_series(name,brand_id) VALUES ('勇士', 11);
INSERT INTO brand_series(name,brand_id) VALUES ('域胜007', 11);
INSERT INTO brand_series(name,brand_id) VALUES ('战旗', 11);
INSERT INTO brand_series(name,brand_id) VALUES ('奔驰C级', 12);
INSERT INTO brand_series(name,brand_id) VALUES ('奔驰E级', 12);
INSERT INTO brand_series(name,brand_id) VALUES ('奔驰GLK级', 12);
INSERT INTO brand_series(name,brand_id) VALUES ('凌特', 12);
INSERT INTO brand_series(name,brand_id) VALUES ('威霆', 12);
INSERT INTO brand_series(name,brand_id) VALUES ('唯雅诺', 12);
INSERT INTO brand_series(name,brand_id) VALUES ('Coupe SUV', 12);
INSERT INTO brand_series(name,brand_id) VALUES ('Ener-G-Force', 12);
INSERT INTO brand_series(name,brand_id) VALUES ('奔驰A级', 12);
INSERT INTO brand_series(name,brand_id) VALUES ('奔驰B级', 12);
INSERT INTO brand_series(name,brand_id) VALUES ('奔驰CLA级', 12);
INSERT INTO brand_series(name,brand_id) VALUES ('奔驰CLS级', 12);
INSERT INTO brand_series(name,brand_id) VALUES ('奔驰CL级', 12);
INSERT INTO brand_series(name,brand_id) VALUES ('奔驰CSC级', 12);
INSERT INTO brand_series(name,brand_id) VALUES ('奔驰C级(进口)', 12);
INSERT INTO brand_series(name,brand_id) VALUES ('奔驰E级(进口)', 12);
INSERT INTO brand_series(name,brand_id) VALUES ('奔驰F125', 12);
INSERT INTO brand_series(name,brand_id) VALUES ('奔驰F800', 12);
INSERT INTO brand_series(name,brand_id) VALUES ('奔驰GLA级(海外)', 12);
INSERT INTO brand_series(name,brand_id) VALUES ('奔驰GLK级(进口)', 12);
INSERT INTO brand_series(name,brand_id) VALUES ('奔驰GL级', 12);
INSERT INTO brand_series(name,brand_id) VALUES ('奔驰G级', 12);
INSERT INTO brand_series(name,brand_id) VALUES ('奔驰M级', 12);
INSERT INTO brand_series(name,brand_id) VALUES ('奔驰R级', 12);
INSERT INTO brand_series(name,brand_id) VALUES ('奔驰SLK级', 12);
INSERT INTO brand_series(name,brand_id) VALUES ('奔驰SL级', 12);
INSERT INTO brand_series(name,brand_id) VALUES ('奔驰S级', 12);
INSERT INTO brand_series(name,brand_id) VALUES ('奔驰V级', 12);
INSERT INTO brand_series(name,brand_id) VALUES ('威霆(进口)', 12);
INSERT INTO brand_series(name,brand_id) VALUES ('唯雅诺(进口)', 12);
INSERT INTO brand_series(name,brand_id) VALUES ('Sprinter', 12);
INSERT INTO brand_series(name,brand_id) VALUES ('奔驰CLK级', 12);
INSERT INTO brand_series(name,brand_id) VALUES ('奔驰SLR级', 12);
INSERT INTO brand_series(name,brand_id) VALUES ('Vision', 12);
INSERT INTO brand_series(name,brand_id) VALUES ('奔驰A级AMG', 12);
INSERT INTO brand_series(name,brand_id) VALUES ('奔驰CLA级AMG', 12);
INSERT INTO brand_series(name,brand_id) VALUES ('奔驰CLS级AMG', 12);
INSERT INTO brand_series(name,brand_id) VALUES ('奔驰CL级AMG', 12);
INSERT INTO brand_series(name,brand_id) VALUES ('奔驰C级AMG', 12);
INSERT INTO brand_series(name,brand_id) VALUES ('奔驰E级AMG', 12);
INSERT INTO brand_series(name,brand_id) VALUES ('奔驰GLA级AMG', 12);
INSERT INTO brand_series(name,brand_id) VALUES ('奔驰GL级AMG', 12);
INSERT INTO brand_series(name,brand_id) VALUES ('奔驰G级AMG', 12);
INSERT INTO brand_series(name,brand_id) VALUES ('奔驰M级AMG', 12);
INSERT INTO brand_series(name,brand_id) VALUES ('奔驰SLK级AMG', 12);
INSERT INTO brand_series(name,brand_id) VALUES ('奔驰SLS级AMG', 12);
INSERT INTO brand_series(name,brand_id) VALUES ('奔驰SL级AMG', 12);
INSERT INTO brand_series(name,brand_id) VALUES ('奔驰S级AMG', 12);
INSERT INTO brand_series(name,brand_id) VALUES ('奔腾B50', 13);
INSERT INTO brand_series(name,brand_id) VALUES ('奔腾B70', 13);
INSERT INTO brand_series(name,brand_id) VALUES ('奔腾B90', 13);
INSERT INTO brand_series(name,brand_id) VALUES ('奔腾X80', 13);
INSERT INTO brand_series(name,brand_id) VALUES ('艾力绅', 14);
INSERT INTO brand_series(name,brand_id) VALUES ('本田CR-V', 14);
INSERT INTO brand_series(name,brand_id) VALUES ('本田S', 14);
INSERT INTO brand_series(name,brand_id) VALUES ('杰德', 14);
INSERT INTO brand_series(name,brand_id) VALUES ('思铂睿', 14);
INSERT INTO brand_series(name,brand_id) VALUES ('思域', 14);
INSERT INTO brand_series(name,brand_id) VALUES ('奥德赛', 15);
INSERT INTO brand_series(name,brand_id) VALUES ('本田C', 15);
INSERT INTO brand_series(name,brand_id) VALUES ('缤智', 15);
INSERT INTO brand_series(name,brand_id) VALUES ('飞度', 15);
INSERT INTO brand_series(name,brand_id) VALUES ('锋范', 15);
INSERT INTO brand_series(name,brand_id) VALUES ('歌诗图', 15);
INSERT INTO brand_series(name,brand_id) VALUES ('凌派', 15);
INSERT INTO brand_series(name,brand_id) VALUES ('雅阁', 15);
INSERT INTO brand_series(name,brand_id) VALUES ('思迪', 15);
INSERT INTO brand_series(name,brand_id) VALUES ('CONCEPT B', 16);
INSERT INTO brand_series(name,brand_id) VALUES ('CONCEPT V', 16);
INSERT INTO brand_series(name,brand_id) VALUES ('EV-Ster', 16);
INSERT INTO brand_series(name,brand_id) VALUES ('INSIGHT', 16);
INSERT INTO brand_series(name,brand_id) VALUES ('Pilot', 16);
INSERT INTO brand_series(name,brand_id) VALUES ('VEZEL', 16);
INSERT INTO brand_series(name,brand_id) VALUES ('奥德赛(海外)', 16);
INSERT INTO brand_series(name,brand_id) VALUES ('本田CR-V(海外)', 16);
INSERT INTO brand_series(name,brand_id) VALUES ('本田CR-Z', 16);
INSERT INTO brand_series(name,brand_id) VALUES ('本田FCX', 16);
INSERT INTO brand_series(name,brand_id) VALUES ('本田NSX', 16);
INSERT INTO brand_series(name,brand_id) VALUES ('本田S660', 16);
INSERT INTO brand_series(name,brand_id) VALUES ('本田Urban', 16);
INSERT INTO brand_series(name,brand_id) VALUES ('飞度(进口)', 16);
INSERT INTO brand_series(name,brand_id) VALUES ('歌诗图(海外)', 16);
INSERT INTO brand_series(name,brand_id) VALUES ('思域(海外)', 16);
INSERT INTO brand_series(name,brand_id) VALUES ('雅阁(海外)', 16);
INSERT INTO brand_series(name,brand_id) VALUES ('本田S2000', 16);
INSERT INTO brand_series(name,brand_id) VALUES ('时韵', 16);
INSERT INTO brand_series(name,brand_id) VALUES ('', 16);
INSERT INTO brand_series(name,brand_id) VALUES ('', 16);
INSERT INTO brand_series(name,brand_id) VALUES ('', 16);
INSERT INTO brand_series(name,brand_id) VALUES ('', 16);
INSERT INTO brand_series(name,brand_id) VALUES ('', 16);
INSERT INTO brand_series(name,brand_id) VALUES ('', 16);
INSERT INTO brand_series(name,brand_id) VALUES ('', 16);
INSERT INTO brand_series(name,brand_id) VALUES ('', 16);
